<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseWindowsConsole>true</UseWindowsConsole>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>S_Cube</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.1.0</Version>
    <Nullable>enable</Nullable>
    <Authors>Sparad</Authors>
    <Description>A console cubing program</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.3.0" />
  </ItemGroup>

</Project>
